version: "2"
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - noctx
    - nolintlint
    - revive
    - sloglint
  settings:
    staticcheck:
      checks:
        - all # Enables all Staticcheck checks by default
        - '-SA1019' # Disables the SA1019 check for deprecated APIs.
formatters:
  enable:
    - gofmt
